### PR TITLE
Pure React form validation solution.

### PR DESCRIPTION
**Pull request by drborges**
This PR provides a React form validation solution built on top of the HTML5 validation API (inspired by https://github.com/drborges/react-legit) and the [Legacy Context API](https://reactjs.org/docs/legacy-context.html) (when we get to React 16 this will have to be migrated to the [New Context API](https://reactjs.org/docs/context.html)) allowing form validations to take place without a lot of state manament and prop-drilling on the developer's part.

It leverages the HTML5 form validation constraints API to create validation rules and provides React callbacks and HOC components that hide away most of the wiring complexity.

Proving this idea a good one, we may consider open source this as a npm package under Power's organization.

# Simple Input Validation

```jsx
<form>
  <Validate trigger="onChange">
    <input type="email" name="email" required />
  </Validate>
</form>
```

The example above triggers the HTML5 validation for the email input field on an `onChange` event. By default, the validation `trigger` is already `onChange`, so the code above could've been written as:

```jsx
<form>
  <Validate>
    <input type="email" name="email" required />
  </Validate>
</form>
```

When the page is rendered the input field is decorated with an specific class name depending on its validation state: `pristine` (no validation has taken place yet), `valid` or `invalid`:

pristine
valid
invalid

That allows different CSS rules to be created to represent these three validation states. One should still be able to use the CSS validation [Pseudo-classes](https://developer.mozilla.org/en-US/docs/Web/CSS/%3Ainvalid) in order to style components based on their validation state (except for the `pristine` state, which isn't supported).

# Validation Groups

Input validations may be grouped within a page to represent validations within different form sections. On the new credit application for instance, each collapsable section of the form presents a validation hint/notification to the user so they know the state of the particular section:

That's wher `ValidationGroup` shines. A validation goup is only valid when all input validations within that group are valid.

```jsx
<form>
  <ValidationGroup>
    <Validate><input type="text" name="name" required /></Validate>
    <Validate><input type="email" name="email" required /></Validate>
  </ValidationGroup>

  <ValidationGroup>
    <Validate><input type="text" name="source" required /></Validate>
    <Validate><input type="number" name="income" required /></Validate>
  </ValidationGroup>
</form>
```

The validation group above is only valid when both `name` and `email` input validations are valid. The resulting `div` rendered by the `ValidationGroup` component is decorated with the same validation classes as the input fields (`validation-pristine`, `validation-valid`, `validation-invalid`).

### Nested Validation Groups

As you may imagine, when validation groups are nested, the parent validation group is only valid when all children validation groups are valid:

```jsx
<form>
  <ValidationGroup>
    <ValidationGroup>
      <Validate><input type="text" name="name" required /></Validate>
      <Validate><input type="email" name="email" required /></Validate>
    </ValidationGroup>

    <ValidationGroup>
      <Validate><input type="text" name="source" required /></Validate>
      <Validate><input type="number" name="income" required /></Validate>
    </ValidationGroup>
  </ValidationGroup>
</form>
```

### Propagating validation state to direct children

Both `Validate` and `ValidationGroup` components accept a `propagate` flag that when `true`, the validation state is propagated down to their direct child component, allowing developers to use it to build more complext rendering logic:

```jsx
const MyInput = ({ valid, ...props }) => (
  <input {...props} className={valid ? "has-no-errors" : "has-errors"} />
)

const Form = () => (
  <form>
    <Validate propagate>
      <MyInput type="email" name="email" required />
    </Validate> 
  </form>
)
```

### CODE REVIEW

**Comment by drborges** [comment]
@xjunior this solution is meant for cases where `redux` isn't used.

**Comment by terryfinn** [comment]
💕 HTML5 Constraint Validations 💕 

Defenders have used constraint validations on a few stories recently. Would be very cool to see this used in more parts of Nitro. Does this allow to see the constraint validation error messages?

**Comment by terryfinn** [comment]
@drborges 
Have you tired evaluating the HTML it generates to test it for accessibility? If we where to open source it, that would be a grate selling point. As someone with a severe learning disability (dyslexia), I value accessible technology, and appreciate when projects make an effort to be accessible.

**Comment by drborges** [comment]
@terryfinn:

>  Does this allow to see the constraint validation error messages?

Currently, the `HTMLInputElement#validationMessage` can be accessed via the input's `onInvalid` event handler:

```jsx
handleInvalidInput = (event) => {
  console.log(event.target.validationMessage)
}

render() {
  return (
    <Validate>
      <input type="email" onInvalid={this.handleInvalidInput} />
    </Validate>
  )
}
```

Another option would be to "propagate" the validation message along with the `valid` flag to the child component as shown in the "Propagating validation state to direct children" section of the PR's description (not yet supported, but could be).

> Have you tried evaluating the HTML it generates to test it for accessibility

Great point! Currently, the validated inputs are only decorated with CSS classes indicating the current input validation state as described on the beginning of the PR's description. However, you brought up a great point. We could also decorate the input fields with [aria-invalid](https://webaim.org/techniques/formvalidation/#ariainvalid) to provide for better accessibility. I'll give that a try. That said, [there is a lot we could improve](https://reactjs.org/docs/accessibility.html) in our React code around accessibility.

I also have plans to support custom validators to provide functionality beyond HTML5 constraints API, such as, async validators  -- API call validations. One use case is email validation which we currently perform through [Kickbox API](https://docs.kickbox.com/docs/using-the-api).

**Note** this is work in progress, so any suggestions on better/more intuitive ways to handle the API (props), naming is very much appreciated.

**Comment by terryfinn** [comment]
> we could also decorate the input fields with aria-invalid to provide for better accessibility. I'll give that a try. That said, there is a lot we could improve in our React code around accessibility.

@drborges There is a huge amount we could do to improve accessibility in Nitro. I only brought it up, because you raised the idea of open sourcing this.

> I also have plans to support custom validators to provide functionality beyond HTML5 constraints API, such as, async validators -- API call validations. One use case is email validation which we currently perform through Kickbox API.

Would you be using the [constraint validation API](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Complex_constraints_using_HTML5_Constraint_API) to set the custom error message?

**Comment by drborges** [comment]
> Would you be using the constraint validation API to set the custom error message?

For the custom validators? Precisely!

Most of the work here is being based on a library I'm working on my free time, in case you are interested, you'd find some examples of how custom validation and the constraint validation API is being used there: https://github.com/drborges/arbor-react-form

**Comment by terryfinn** [comment]
Very cool. I will take a closer look.

**Comment by drborges** [comment]
Closing for the same reason as https://github.com/powerhome/nitro-storybook/pull/65.

This solution fits many use cases but falls short for some of our custom input components which don't expose an API/props consistent with HTML input elements.

**Pull request closed without merging**
